/// Trilingual localization dictionary for Sri Lankan fishermen.
class MarineLocale {
  static const Map<String, Map<String, String>> _strings = {
    'si': {
      'app_name': 'ලෙල්ලම - සාගර තොරතුරු',
      'pfz_title': 'විභව මත්ස්‍ය කලාප (PFZ)',
      'weather_title': 'සාගර කාලගුණය',
      'alerts_title': 'ආරක්ෂිත නිවේදන',
      'map_view': 'සිතියම',
      'list_view': 'කලාප ලැයිස්තුව',
      'sync_now': 'දත්ත යාවත්කාලීන කරන්න',
      'offline_mode': 'නොබැඳි මාදිලිය (නිරවුල්)',
      'online_mode': 'සම්බන්ධ වී ඇත',
      'last_sync': 'අවසන් යාවත්කාලීනය',
      'wave_height': 'රළ උස',
      'wind_wave': 'සුළං රළ',
      'swell_wave': 'දිය රැල්ල',
      'current': 'දියවැල් වේගය',
      'confidence': 'විශ්වාසනීයත්වය',
      'distance': 'දුර',
      'bearing': 'දිශාව',
      'sst': 'මුහුදු උෂ්ණත්වය',
      'safe': 'සාමාන්‍ය මුහුදු තත්ත්වය',
      'warning': 'අවවාදයයි: රළු මුහුද',
      'danger': 'අනතුරුදායකයි: වහාම ආරක්ෂිත වන්න',
      'no_alerts': 'ක්‍රියාකාරී කාලගුණ අනතුරු ඇඟවීම් නොමැත',
      'meters': 'මීටර්',
      'nautical_miles': 'නාවික සැතපුම්',
      'knots': 'නොට්ස්',
      'deg_c': '°C',
    },
    'ta': {
      'app_name': 'லெல்லம - கடல் தகவல்',
      'pfz_title': 'சாத்தியமான மீன்பிடி மண்டலங்கள்',
      'weather_title': 'கடல் வானிலை',
      'alerts_title': 'பாதுகாப்பு எச்சரிக்கைகள்',
      'map_view': 'வரைபடம்',
      'list_view': 'மண்டல பட்டியல்',
      'sync_now': 'தரவை ஒத்திசைக்கவும்',
      'offline_mode': 'ஆஃப்லைன் நிலை (பாதுகாப்பானது)',
      'online_mode': 'இணைக்கப்பட்டுள்ளது',
      'last_sync': 'கடைசி ஒத்திசைவு',
      'wave_height': 'அலை உயரம்',
      'wind_wave': 'காற்று அலை',
      'swell_wave': 'கடல் அலை',
      'current': 'நீரோட்ட வேகம்',
      'confidence': 'நம்பகத்தன்மை',
      'distance': 'தூரம்',
      'bearing': 'திசை',
      'sst': 'கடல் வெப்பநிலை',
      'safe': 'இயல்பான கடல் நிலைமை',
      'warning': 'எச்சரிக்கை: கொந்தளிப்பான கடல்',
      'danger': 'ஆபத்து: உடனடியாக பாதுகாப்பான இடம் செல்லவும்',
      'no_alerts': 'செயலில் உள்ள எச்சரிக்கைகள் இல்லை',
      'meters': 'மீட்டர்கள்',
      'nautical_miles': 'கடல் மைல்கள்',
      'knots': 'நாட்கள்',
      'deg_c': '°C',
    },
    'en': {
      'app_name': 'LELLAMA Marine Tech',
      'pfz_title': 'Potential Fishing Zones (PFZ)',
      'weather_title': 'Marine Weather',
      'alerts_title': 'Safety Warnings',
      'map_view': 'Map View',
      'list_view': 'Zone Directory',
      'sync_now': 'Sync Offshore Bundle',
      'offline_mode': 'OFFLINE READY (CACHED)',
      'online_mode': 'ONLINE CONNECTED',
      'last_sync': 'Last Synced',
      'wave_height': 'Wave Height',
      'wind_wave': 'Wind Waves',
      'swell_wave': 'Swell Waves',
      'current': 'Ocean Current',
      'confidence': 'Confidence',
      'distance': 'Distance',
      'bearing': 'Bearing',
      'sst': 'Sea Temp',
      'safe': 'Sea State Normal',
      'warning': 'WARNING: Rough Sea Conditions',
      'danger': 'DANGER: Seek Safe Harbor',
      'no_alerts': 'No active marine weather warnings',
      'meters': 'm',
      'nautical_miles': 'NM',
      'knots': 'kts',
      'deg_c': '°C',
    },
  };

  static String text(String key, String langCode) {
    final lang = _strings.containsKey(langCode) ? langCode : 'si';
    return _strings[lang]?[key] ?? _strings['en']?[key] ?? key;
  }
}
